/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public bootstrap info for the login/setup screens */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the first admin (only while no users exist) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetupRequest"];
                };
            };
            responses: {
                201: components["responses"]["UserResponse"];
                404: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local login; sets the session cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                200: components["responses"]["UserResponse"];
                401: components["responses"]["Error"];
                423: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["UserResponse"];
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change own password (local accounts only) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description Changed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start OIDC authorization code flow (302 to provider) */
        get: {
            parameters: {
                query?: {
                    /** @description SPA path to return to after login (must start with /) */
                    next?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to provider */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC redirect URI (302 to SPA; on failure 302 to /login?error=code) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users: components["schemas"]["User"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                201: components["responses"]["UserResponse"];
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["UserResponse"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                200: components["responses"]["UserResponse"];
                /** @description Would remove last admin */
                409: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/users/{userId}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Admin sets a user's password */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description Set */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        /** @description Full replace. `auth.oidc.client_secret` empty string means "keep existing". */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/oidc/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover the issuer and report whether the configuration looks valid */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OIDCSettings"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            issuer?: string;
                            authorization_endpoint?: string;
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/update-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query GitHub releases for a newer manager version now */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppUpdateInfo"];
                    };
                };
                502: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download and install a newer manager release, then restart the manager.
         *     Game server instances are systemd units and keep running. Returns a job;
         *     the SSE stream drops when the manager restarts and the UI reconnects.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Tag to install; omit for latest */
                        version?: string;
                    };
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            instances: components["schemas"]["Instance"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an instance and (by default) enqueue the install job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateInstanceRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            instance: components["schemas"]["Instance"];
                            job?: components["schemas"]["Job"];
                        };
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["InstanceResponse"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    /** @description Also remove the instance directory (game files, saves, backups) */
                    delete_files?: boolean;
                };
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Instance running */
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update display name and/or config; sets pending_restart if running
         * @description Fields omitted from `config` keep their stored values, with one exception:
         *     `config.modifiers` is a set, so when it is present it replaces the stored
         *     modifiers wholesale (a rule absent from the object becomes unset).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateInstanceRequest"];
                };
            };
            responses: {
                200: components["responses"]["InstanceResponse"];
                422: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/instances/{instanceId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["InstanceStatusResponse"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["InstanceStatusResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["InstanceStatusResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["InstanceStatusResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install or validate game files with SteamCMD */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: components["responses"]["JobResponse"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update game files (stops/starts around the update if requested) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StopIfRunning"];
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/update-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Steam for the latest public build id now */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateInfo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tail of console.log */
        get: {
            parameters: {
                query?: {
                    lines?: number;
                };
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            lines: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/logs/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlayersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/lists/{listKind}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
                listKind: components["schemas"]["ListKind"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    listKind: components["schemas"]["ListKind"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlayerList"];
                    };
                };
            };
        };
        /** Replace the list file (Valheim reloads it live) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    listKind: components["schemas"]["ListKind"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlayerList"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlayerList"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/worlds": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            worlds: components["schemas"]["World"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Upload a world (.db + .fwl files, or one zip containing them) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        files?: string[];
                        /** @default false */
                        overwrite?: boolean;
                    };
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/worlds/{worldName}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
                worldName: components["parameters"]["worldName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an inactive world */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    worldName: components["parameters"]["worldName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/worlds/{worldName}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate the active world: take a backup, delete its save files and let
         *     Valheim create a fresh world (new random seed) with the same name on the
         *     next start. Only the active world can be regenerated; delete inactive ones.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    worldName: components["parameters"]["worldName"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StopIfRunning"];
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/worlds/{worldName}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    worldName: components["parameters"]["worldName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/backups": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            backups: components["schemas"]["Backup"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a manual backup now */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        note?: string;
                    };
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/backups/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a backup zip previously downloaded from this UI */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            backup: components["schemas"]["Backup"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/backups/{backupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
                backupId: components["parameters"]["backupId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    backupId: components["parameters"]["backupId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/backups/{backupId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    backupId: components["parameters"]["backupId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/backups/{backupId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a backup (creates a pre_restore backup first; instance must be stopped) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    backupId: components["parameters"]["backupId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StopIfRunning"];
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            schedules: components["schemas"]["Schedule"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScheduleInput"];
                };
            };
            responses: {
                201: components["responses"]["ScheduleResponse"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
                scheduleId: components["parameters"]["scheduleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    scheduleId: components["parameters"]["scheduleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    scheduleId: components["parameters"]["scheduleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScheduleInput"];
                };
            };
            responses: {
                200: components["responses"]["ScheduleResponse"];
            };
        };
        trace?: never;
    };
    "/instances/{instanceId}/schedules/{scheduleId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the schedule's action now */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    scheduleId: components["parameters"]["scheduleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: components["responses"]["JobResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/mods": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModsOverview"];
                    };
                };
            };
        };
        put?: never;
        /** Install a Thunderstore package (and its dependencies) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        owner: string;
                        name: string;
                        /** @description Omit for latest */
                        version?: string;
                    };
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/mods/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a mod zip (Thunderstore layout with manifest.json) or a single .dll */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/mods/bepinex": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install or upgrade BepInEx (instance must be stopped) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StopIfRunning"];
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /** Enable or disable the BepInEx loader */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        enabled: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModsOverview"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/instances/{instanceId}/mods/{modId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
                modId: components["parameters"]["modId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    modId: components["parameters"]["modId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: components["responses"]["JobResponse"];
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    modId: components["parameters"]["modId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        enabled: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            mod: components["schemas"]["Mod"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/instances/{instanceId}/mods/{modId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update a Thunderstore mod to the latest (or given) version */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    modId: components["parameters"]["modId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        version?: string;
                    };
                };
            };
            responses: {
                202: components["responses"]["JobResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/mods/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            files: components["schemas"]["ConfigFileInfo"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/mods/configs/{fileName}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["instanceId"];
                fileName: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    fileName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigFile"];
                    };
                };
            };
        };
        /** @description Send either `raw` (whole file) or `values` (key updates, comments preserved). */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instanceId: components["parameters"]["instanceId"];
                    fileName: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfigFileUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigFile"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thunderstore/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    category?: string;
                    sort?: "rating" | "downloads" | "updated" | "name";
                    include_deprecated?: boolean;
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PackageSearchResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thunderstore/packages/{owner}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Package"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thunderstore/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            categories: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thunderstore/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: components["responses"]["JobResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    instance?: string;
                    status?: components["schemas"]["JobStatus"];
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            jobs: components["schemas"]["Job"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["jobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["JobResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["jobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            lines: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["jobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["JobResponse"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream
         * @description `text/event-stream`. Event names and JSON payloads:
         *     - `instance.status`: InstanceStatus (with instance_id)
         *     - `instance.log`: { instance_id, line }
         *     - `instance.players`: { instance_id, online: OnlinePlayer[] }
         *     - `job.updated`: Job
         *     - `job.log`: { job_id, line }
         *     - `update.available`: UpdateInfo
         *     - `app.update_available`: AppUpdateInfo
         *     - `heartbeat`: { ts }
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter instance-scoped events */
                    instance?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    instance?: string;
                    user?: string;
                    limit?: number;
                    before?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries: components["schemas"]["AuditEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /**
                 * @description One of: unauthorized, forbidden, not_found, validation_failed, conflict,
                 *     instance_running, instance_not_installed, instance_busy, port_in_use,
                 *     last_admin, invalid_credentials, account_locked, account_disabled,
                 *     setup_done, oidc_disabled, oidc_error, steamcmd_missing, bepinex_missing,
                 *     package_not_found, upstream_error, internal
                 */
                code: string;
                message: string;
                details?: {
                    fields?: {
                        field: string;
                        message: string;
                    }[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        Role: "viewer" | "operator" | "admin";
        AuthStatus: {
            needs_setup: boolean;
            local_login_enabled: boolean;
            oidc_enabled: boolean;
            oidc_provider_name?: string;
            app_version?: string;
        };
        SetupRequest: {
            username: string;
            password: string;
            display_name?: string;
            /** Format: email */
            email?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        User: {
            id: number;
            username: string;
            display_name?: string;
            email?: string;
            role: components["schemas"]["Role"];
            disabled: boolean;
            /** @description false for OIDC-only accounts */
            has_password: boolean;
            identities: {
                provider: string;
                subject: string;
            }[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at?: string;
        };
        CreateUserRequest: {
            username: string;
            /** @description Omit for OIDC-only accounts */
            password?: string;
            display_name?: string;
            /** Format: email */
            email?: string;
            role: components["schemas"]["Role"];
        };
        UpdateUserRequest: {
            display_name?: string;
            /** Format: email */
            email?: string;
            role?: components["schemas"]["Role"];
            disabled?: boolean;
        };
        OIDCSettings: {
            enabled: boolean;
            /** @default SSO */
            provider_name: string;
            issuer_url?: string;
            client_id?: string;
            /** @description Write-only. Empty on read; empty on write keeps the stored value. */
            client_secret?: string;
            /**
             * @default [
             *       "openid",
             *       "profile",
             *       "email",
             *       "groups"
             *     ]
             */
            scopes: string[];
            /** @default groups */
            groups_claim: string;
            /** @description group name → role; highest matching role wins */
            role_mapping?: {
                [key: string]: components["schemas"]["Role"];
            };
            /**
             * @description Role for users without a mapped group; deny blocks login
             * @default viewer
             * @enum {string}
             */
            default_role: "viewer" | "operator" | "admin" | "deny";
            /** @default true */
            auto_create_users: boolean;
            /**
             * @description Link a login without an email_verified claim to a local account with the same email (never an admin account)
             * @default false
             */
            link_unverified_email: boolean;
            /**
             * @description Re-apply role mapping on every login
             * @default true
             */
            sync_roles: boolean;
            /** @description Computed from base_url; register this at the provider */
            readonly redirect_uri?: string;
        };
        Settings: {
            auth: {
                /** @default true */
                local_login_enabled: boolean;
                oidc: components["schemas"]["OIDCSettings"];
            };
            updates: {
                /**
                 * @description 0 disables
                 * @default 60
                 */
                check_interval_minutes: number;
            };
            thunderstore: {
                /** @default 6 */
                index_refresh_hours: number;
            };
            app: {
                /**
                 * @description 0 disables release polling
                 * @default 6
                 */
                update_check_hours: number;
                /**
                 * @description Install new releases automatically when no players are online on any instance
                 * @default false
                 */
                auto_upgrade: boolean;
            };
        };
        SystemInfo: {
            version: string;
            commit?: string;
            data_dir: string;
            /** @enum {string} */
            supervisor: "systemd" | "direct";
            steamcmd_installed: boolean;
            /** Format: int64 */
            disk_free_bytes: number;
            /** Format: int64 */
            disk_total_bytes: number;
            /** Format: date-time */
            started_at: string;
            /** @description Last known public Valheim build id */
            latest_buildid?: string;
            /** Format: date-time */
            buildid_checked_at?: string;
            app_update?: components["schemas"]["AppUpdateInfo"];
            host?: components["schemas"]["HostMetrics"];
        };
        /** @description Manager host resource usage, sampled from /proc. */
        HostMetrics: {
            /** @description CPU utilisation across all cores */
            cpu_percent: number;
            cpu_count: number;
            load_avg_1: number;
            /** Format: int64 */
            mem_total_bytes: number;
            /**
             * Format: int64
             * @description MemTotal minus MemAvailable
             */
            mem_used_bytes: number;
        };
        AppUpdateInfo: {
            current_version: string;
            latest_version?: string;
            update_available: boolean;
            /** Format: date-time */
            checked_at?: string;
            release_url?: string;
            /** @description Markdown body of the release */
            release_notes?: string;
            /** Format: date-time */
            published_at?: string;
            /** @description The running binary's location is writable by the manager */
            can_self_upgrade: boolean;
            /** @description Why self-upgrade is unavailable */
            reason?: string;
            /** @description Human summary of the last check, e.g. "no releases published yet" or "running an untagged build" */
            message?: string;
            /** @description Version kept for rollback */
            previous_version?: string;
        };
        /** @enum {string} */
        InstanceState: "not_installed" | "stopped" | "starting" | "running" | "stopping" | "failed";
        Modifiers: {
            /** @enum {string} */
            combat?: "veryeasy" | "easy" | "hard" | "veryhard";
            /** @enum {string} */
            deathpenalty?: "casual" | "veryeasy" | "easy" | "hard" | "hardcore";
            /** @enum {string} */
            resources?: "muchless" | "less" | "more" | "muchmore" | "most";
            /** @enum {string} */
            raids?: "none" | "muchless" | "less" | "more" | "muchmore";
            /** @enum {string} */
            portals?: "casual" | "hard" | "veryhard";
        };
        InstanceConfig: {
            name: string;
            world: string;
            /** @description Masked as "********" for viewers */
            password: string;
            port: number;
            public: boolean;
            crossplay: boolean;
            /** @enum {string} */
            preset?: "" | "normal" | "casual" | "easy" | "hard" | "hardcore" | "immersive" | "hammer";
            modifiers?: components["schemas"]["Modifiers"];
            setkeys?: ("nobuildcost" | "playerevents" | "passivemobs" | "nomap" | "fire")[];
            /** @default 1800 */
            save_interval_sec: number;
            /** @default 4 */
            game_backups: number;
            /** @default 7200 */
            game_backup_short_sec: number;
            /** @default 43200 */
            game_backup_long_sec: number;
            extra_args?: string[];
            /** @default false */
            bepinex_enabled: boolean;
            /** @default 10 */
            backup_keep_last: number;
            /** @default 30 */
            backup_keep_days: number;
            /** @default true */
            backup_before_update: boolean;
        };
        A2SInfo: {
            server_name: string;
            map?: string;
            players: number;
            max_players: number;
            version?: string;
            password_protected?: boolean;
            /** Format: date-time */
            queried_at?: string;
        };
        InstanceStatus: {
            instance_id: string;
            state: components["schemas"]["InstanceState"];
            /** @description World loaded and accepting players (from log) */
            ready: boolean;
            pid?: number;
            /** Format: date-time */
            since?: string;
            autostart: boolean;
            pending_restart: boolean;
            detail?: string;
            players_online: number;
            max_players?: number;
            join_code?: string;
            a2s?: components["schemas"]["A2SInfo"];
            installed_buildid?: string;
            update_available?: boolean;
            bepinex_installed?: boolean;
            bepinex_enabled?: boolean;
            active_job?: components["schemas"]["Job"];
            /** @description Game process CPU */
            cpu_percent?: number;
            /**
             * Format: int64
             * @description Game process resident memory
             */
            memory_bytes?: number;
        };
        Instance: {
            id: string;
            /** @description Display name in the UI (not the in-game server name) */
            name: string;
            config: components["schemas"]["InstanceConfig"];
            status: components["schemas"]["InstanceStatus"];
            paths?: {
                root?: string;
                server?: string;
                save?: string;
                backups?: string;
                logs?: string;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateInstanceRequest: {
            id: string;
            name: string;
            config: components["schemas"]["InstanceConfig"];
            /** @default false */
            autostart: boolean;
            /**
             * @description Enqueue the SteamCMD install job immediately
             * @default true
             */
            install: boolean;
        };
        UpdateInstanceRequest: {
            name?: string;
            config?: components["schemas"]["InstanceConfig"];
            autostart?: boolean;
        };
        StopIfRunning: {
            /**
             * @description Stop the instance for the operation and start it again afterwards
             * @default false
             */
            stop_if_running: boolean;
        };
        UpdateInfo: {
            instance_id: string;
            installed_buildid?: string;
            latest_buildid?: string;
            update_available: boolean;
            /** Format: date-time */
            checked_at?: string;
        };
        OnlinePlayer: {
            platform_id?: string;
            name: string;
            /** Format: date-time */
            connected_at?: string;
        };
        KnownPlayer: {
            platform_id: string;
            name?: string;
            /** Format: date-time */
            first_seen_at: string;
            /** Format: date-time */
            last_seen_at: string;
            session_count: number;
        };
        PlayersResponse: {
            online: components["schemas"]["OnlinePlayer"][];
            online_count?: number;
            /** @enum {string} */
            count_source: "a2s" | "log" | "none";
            known: components["schemas"]["KnownPlayer"][];
        };
        /** @enum {string} */
        ListKind: "admin" | "banned" | "permitted";
        PlayerList: {
            kind: components["schemas"]["ListKind"];
            entries: {
                /** @description Platform id, e.g. Steam_76561198000000000 or 76561198000000000 */
                id: string;
                /** @description Stored as a trailing // comment on the same line */
                comment?: string;
            }[];
        };
        World: {
            name: string;
            active: boolean;
            /** Format: int64 */
            size_bytes: number;
            /** Format: date-time */
            modified_at: string;
            has_db?: boolean;
            has_fwl?: boolean;
        };
        /** @enum {string} */
        BackupKind: "manual" | "scheduled" | "pre_update" | "pre_restore" | "uploaded";
        Backup: {
            id: number;
            instance_id: string;
            world: string;
            kind: components["schemas"]["BackupKind"];
            filename: string;
            /** Format: int64 */
            size_bytes: number;
            note?: string;
            /** Format: date-time */
            created_at: string;
            /** @description DB row exists but file is gone */
            missing?: boolean;
        };
        /** @enum {string} */
        ScheduleKind: "restart" | "backup" | "update";
        ScheduleInput: {
            kind: components["schemas"]["ScheduleKind"];
            /** @description Standard 5-field cron, host timezone */
            cron: string;
            enabled: boolean;
            /** @default true */
            only_when_empty: boolean;
            note?: string;
        };
        Schedule: components["schemas"]["ScheduleInput"] & {
            id: number;
            instance_id: string;
            /** Format: date-time */
            next_run_at?: string;
            /** Format: date-time */
            last_run_at?: string;
            /** @enum {string} */
            last_result?: "ok" | "skipped" | "failed";
            last_job_id?: string;
        };
        Mod: {
            id: number;
            instance_id: string;
            /** @enum {string} */
            source: "thunderstore" | "manual";
            owner: string;
            name: string;
            version: string;
            enabled: boolean;
            /** @description From the Thunderstore index */
            latest_version?: string;
            update_available?: boolean;
            dependencies?: string[];
            icon_url?: string;
            website_url?: string;
            /** Format: date-time */
            installed_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ModsOverview: {
            bepinex: {
                installed: boolean;
                enabled: boolean;
                version?: string;
                latest_version?: string;
            };
            mods: components["schemas"]["Mod"][];
            pending_restart?: boolean;
        };
        ConfigFileInfo: {
            name: string;
            /** Format: int64 */
            size_bytes: number;
            /** Format: date-time */
            modified_at: string;
        };
        ConfigEntry: {
            section: string;
            key: string;
            value: string;
            description?: string;
            /** @description From "# Setting type:" e.g. Boolean, Int32, Single, String, KeyCode, enum name */
            type?: string;
            default_value?: string;
            acceptable_values?: string[];
            range?: {
                min?: string;
                max?: string;
            };
        };
        ConfigFile: {
            name: string;
            raw: string;
            entries: components["schemas"]["ConfigEntry"][];
            /** Format: date-time */
            modified_at?: string;
        };
        ConfigFileUpdate: {
            raw?: string;
            values?: {
                section: string;
                key: string;
                value: string;
            }[];
        };
        PackageVersion: {
            version: string;
            description?: string;
            download_url: string;
            dependencies: string[];
            downloads?: number;
            /** Format: int64 */
            file_size?: number;
            /** Format: date-time */
            date_created: string;
        };
        PackageSummary: {
            owner: string;
            name: string;
            full_name: string;
            description?: string;
            icon_url?: string;
            package_url?: string;
            latest_version: string;
            rating_score: number;
            total_downloads: number;
            is_deprecated: boolean;
            is_pinned?: boolean;
            categories: string[];
            /** Format: date-time */
            date_updated: string;
        };
        Package: components["schemas"]["PackageSummary"] & {
            website_url?: string;
            versions: components["schemas"]["PackageVersion"][];
        };
        PackageSearchResult: {
            packages: components["schemas"]["PackageSummary"][];
            total: number;
            page: number;
            page_size: number;
            /** Format: date-time */
            index_updated_at: string;
        };
        /** @enum {string} */
        JobType: "install" | "update" | "backup" | "restore" | "world_import" | "world_regenerate" | "mod_install" | "mod_update" | "mod_uninstall" | "bepinex_install" | "scheduled_restart" | "thunderstore_refresh" | "self_upgrade";
        /** @enum {string} */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        Job: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["JobType"];
            instance_id?: string;
            status: components["schemas"]["JobStatus"];
            /** @description Human readable */
            title?: string;
            requested_by?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            error?: string;
            summary?: {
                [key: string]: unknown;
            };
        };
        /** @description One changed field. A missing `from` means it was unset before, a missing `to` that it was cleared. */
        AuditChange: {
            /** @example config.modifiers.portals */
            path: string;
            from?: unknown;
            to?: unknown;
        };
        AuditEntry: {
            id: number;
            /** Format: date-time */
            ts: string;
            user_id?: number;
            username?: string;
            action: string;
            instance_id?: string;
            target?: string;
            /**
             * @description Free-form per action. Update actions (instance.update, settings.update,
             *     user.update, schedule.update, players.list.update) carry `changes`, a
             *     field-level diff of what the request changed; secrets are masked as "••••••".
             */
            details?: {
                changes?: components["schemas"]["AuditChange"][];
            } & {
                [key: string]: unknown;
            };
            ip?: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description User */
        UserResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    user: components["schemas"]["User"];
                };
            };
        };
        /** @description Instance */
        InstanceResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    instance: components["schemas"]["Instance"];
                };
            };
        };
        /** @description Status */
        InstanceStatusResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    status: components["schemas"]["InstanceStatus"];
                };
            };
        };
        /** @description Job */
        JobResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    job: components["schemas"]["Job"];
                };
            };
        };
        /** @description Schedule */
        ScheduleResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    schedule: components["schemas"]["Schedule"];
                };
            };
        };
    };
    parameters: {
        instanceId: string;
        userId: number;
        backupId: number;
        scheduleId: number;
        modId: number;
        jobId: string;
        worldName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
