// Convenience aliases over the generated OpenAPI schema. Never hand-write API
// shapes; regenerate schema.d.ts with `npm run gen:api` when docs/openapi.yaml changes.
import type { components } from './schema'

export type Schemas = components['schemas']
export type Role = Schemas['Role']
export type User = Schemas['User']
export type AuthStatus = Schemas['AuthStatus']
export type SetupRequest = Schemas['SetupRequest']
export type LoginRequest = Schemas['LoginRequest']
export type ChangePasswordRequest = Schemas['ChangePasswordRequest']
export type CreateUserRequest = Schemas['CreateUserRequest']
export type UpdateUserRequest = Schemas['UpdateUserRequest']
export type Settings = Schemas['Settings']
export type OIDCSettings = Schemas['OIDCSettings']
export type SystemInfo = Schemas['SystemInfo']
export type AppUpdateInfo = Schemas['AppUpdateInfo']
export type AppUpgradeState = Schemas['AppUpgradeState']
export type Instance = Schemas['Instance']
export type InstanceConfig = Schemas['InstanceConfig']
export type Modifiers = Schemas['Modifiers']
export type InstanceStatus = Schemas['InstanceStatus']
export type InstanceState = Schemas['InstanceState']
export type CreateInstanceRequest = Schemas['CreateInstanceRequest']
export type UpdateInstanceRequest = Schemas['UpdateInstanceRequest']
export type UpdateInfo = Schemas['UpdateInfo']
export type PlayersResponse = Schemas['PlayersResponse']
export type KnownPlayer = Schemas['KnownPlayer']
export type OnlinePlayer = Schemas['OnlinePlayer']
export type PlayerList = Schemas['PlayerList']
export type ListKind = Schemas['ListKind']
export type World = Schemas['World']
export type BackupKind = Schemas['BackupKind']
export type Backup = Schemas['Backup']
export type ScheduleKind = Schemas['ScheduleKind']
export type Schedule = Schemas['Schedule']
export type ScheduleInput = Schemas['ScheduleInput']
export type Mod = Schemas['Mod']
export type ModsOverview = Schemas['ModsOverview']
export type ConfigFile = Schemas['ConfigFile']
export type ConfigFileInfo = Schemas['ConfigFileInfo']
export type ConfigEntry = Schemas['ConfigEntry']
export type ConfigFileUpdate = Schemas['ConfigFileUpdate']
export type StopIfRunning = Schemas['StopIfRunning']
export type PackageSummary = Schemas['PackageSummary']
export type Package = Schemas['Package']
export type PackageVersion = Schemas['PackageVersion']
export type PackageSearchResult = Schemas['PackageSearchResult']
export type Registry = Schemas['Registry']
export type Job = Schemas['Job']
export type JobStatus = Schemas['JobStatus']
export type JobType = Schemas['JobType']
export type AuditEntry = Schemas['AuditEntry']
export type ErrorResponse = Schemas['ErrorResponse']

export const ROLE_LEVEL: Record<Role, number> = { viewer: 1, operator: 2, admin: 3 }
export function roleAtLeast(role: Role | undefined, min: Role): boolean {
  return !!role && ROLE_LEVEL[role] >= ROLE_LEVEL[min]
}
export type AgentInfo = Schemas['AgentInfo']
export type AgentStatus = Schemas['AgentStatus']
export type AgentPlayer = Schemas['AgentPlayer']
export type AgentCommandRequest = Schemas['AgentCommandRequest']
export type AgentCommandResult = Schemas['AgentCommandResult']
export type AgentWorldEvent = Schemas['AgentWorldEvent']
export type AgentCatalog = Schemas['AgentCatalog']
export type AgentEventDef = Schemas['AgentEventDef']
export type AgentChat = Schemas['AgentChat']
export type AgentChatMessage = Schemas['AgentChatMessage']
export type InstanceMap = Schemas['InstanceMap']
export type MapInfo = Schemas['MapInfo']
export type MapObject = Schemas['MapObject']
export type MapLocation = Schemas['MapLocation']
export type MapPin = Schemas['MapPin']
export type MapRenderRequest = Schemas['MapRenderRequest']
export type ExploredInfo = Schemas['ExploredInfo']
